version: '2'

services:
  db:
    image: postgres:12.7
    environment:
      POSTGRES_PASSWORD: interview
      POSTGRES_DB: interview
      POSTGRES_USER: interview
    ports:
      - 25432:5432
    volumes:
      - ./docker/pg:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
