version: '2'

services:
  app:
    image: node:14
    ports:
      - 3030:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
    working_dir: /app
    command: npm start

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: interview
      POSTGRES_DB: interview
      POSTGRES_USER: interview
    ports:
      - 25432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
